#ifndef TOOLMATCHSKELETON_GLOBAL_H
#define TOOLMATCHSKELETON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOOLMATCHSKELETON_LIBRARY)
#  define TOOLMATCHSKELETONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TOOLMATCHSKELETONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TOOLMATCHSKELETON_GLOBAL_H
