#ifndef VERTICALPOINT_GLOBAL_H
#define VERTICALPOINT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VERTICALPOINT_LIBRARY)
#  define VERTICALPOINTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VERTICALPOINTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VERTICALPOINT_GLOBAL_H
