#ifndef STATISTIC_GLOBAL_H
#define STATISTIC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STATISTIC_LIBRARY)
#  define STATISTICSHARED_EXPORT Q_DECL_EXPORT
#else
#  define STATISTICSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STATISTIC_GLOBAL_H
