#ifndef PRETREATMENT_GLOBAL_H
#define PRETREATMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PRETREATMENT_LIBRARY)
#  define PRETREATMENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PRETREATMENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PRETREATMENT_GLOBAL_H
