#ifndef TOOLSCALECALC_GLOBAL_H
#define TOOLSCALECALC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOOLSCALECALC_LIBRARY)
#  define TOOLSCALECALCSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TOOLSCALECALCSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TOOLSCALECALC_GLOBAL_H
