#ifndef L2LCROSSPOINT_GLOBAL_H
#define L2LCROSSPOINT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(L2LCROSSPOINT_LIBRARY)
#  define L2LCROSSPOINTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define L2LCROSSPOINTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // L2LCROSSPOINT_GLOBAL_H
