#ifndef TOOLMATCHPOLAR_GLOBAL_H
#define TOOLMATCHPOLAR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOOLMATCHPOLAR_LIBRARY)
#  define TOOLMATCHPOLARSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TOOLMATCHPOLARSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TOOLMATCHPOLAR_GLOBAL_H
