#ifndef TOOLMATCHBASEPOINT_GLOBAL_H
#define TOOLMATCHBASEPOINT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOOLMATCHBASEPOINT_LIBRARY)
#  define TOOLMATCHBASEPOINTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TOOLMATCHBASEPOINTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TOOLMATCHBASEPOINT_GLOBAL_H
