#ifndef TOOLLOGICDATAJUDGE_GLOBAL_H
#define TOOLLOGICDATAJUDGE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOOLLOGICDATAJUDGE_LIBRARY)
#  define TOOLLOGICDATAJUDGESHARED_EXPORT Q_DECL_EXPORT
#else
#  define TOOLLOGICDATAJUDGESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TOOLLOGICDATAJUDGE_GLOBAL_H
