#ifndef P2LDISTANCE_GLOBAL_H
#define P2LDISTANCE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(P2LDISTANCE_LIBRARY)
#  define P2LDISTANCESHARED_EXPORT Q_DECL_EXPORT
#else
#  define P2LDISTANCESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // P2LDISTANCE_GLOBAL_H
