#ifndef LOGICCOMMANDJUMP_GLOBAL_H
#define LOGICCOMMANDJUMP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LOGICCOMMANDJUMP_LIBRARY)
#  define LOGICCOMMANDJUMPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LOGICCOMMANDJUMPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LOGICCOMMANDJUMP_GLOBAL_H
