#ifndef HANSROBOTHPROTOCOL_GLOBAL_H
#define HANSROBOTHPROTOCOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HANSROBOTHPROTOCOL_LIBRARY)
#  define HANSROBOTHPROTOCOLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HANSROBOTHPROTOCOLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HANSROBOTHPROTOCOL_GLOBAL_H
