#ifndef TOOLMATCHSAMPLE_GLOBAL_H
#define TOOLMATCHSAMPLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOOLMATCHSAMPLE_LIBRARY)
#  define TOOLMATCHSAMPLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define TOOLMATCHSAMPLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TOOLMATCHSAMPLE_GLOBAL_H
