#ifndef MEANBRIGHTNESS_GLOBAL_H
#define MEANBRIGHTNESS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MEANBRIGHTNESS_LIBRARY)
#  define MEANBRIGHTNESSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MEANBRIGHTNESSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MEANBRIGHTNESS_GLOBAL_H
