#ifndef LEARNINGDIALOG_GLOBAL_H
#define LEARNINGDIALOG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LEARNINGDIALOG_LIBRARY)
#  define LEARNINGDIALOGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LEARNINGDIALOGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LEARNINGDIALOG_GLOBAL_H
