#ifndef USERDEFINED_GLOBAL_H
#define USERDEFINED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(USERDEFINED_LIBRARY)
#  define USERDEFINEDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define USERDEFINEDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // USERDEFINED_GLOBAL_H
