#ifndef TOOLMATCHBASELINE_GLOBAL_H
#define TOOLMATCHBASELINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOOLMATCHBASELINE_LIBRARY)
#  define TOOLMATCHBASELINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define TOOLMATCHBASELINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TOOLMATCHBASELINE_GLOBAL_H
