#ifndef POLYGONCENTER_GLOBAL_H
#define POLYGONCENTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(POLYGONCENTER_LIBRARY)
#  define POLYGONCENTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define POLYGONCENTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // POLYGONCENTER_GLOBAL_H
