#ifndef TOOLLOGICDELAY_GLOBAL_H
#define TOOLLOGICDELAY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOOLLOGICDELAY_LIBRARY)
#  define TOOLLOGICDELAYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TOOLLOGICDELAYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TOOLLOGICDELAY_GLOBAL_H
