#ifndef GRAYSTATISTICS_GLOBAL_H
#define GRAYSTATISTICS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GRAYSTATISTICS_LIBRARY)
#  define GRAYSTATISTICSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GRAYSTATISTICSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GRAYSTATISTICS_GLOBAL_H
