#ifndef CONTOURPOINTS_GLOBAL_H
#define CONTOURPOINTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTOURPOINTS_LIBRARY)
#  define CONTOURPOINTSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONTOURPOINTSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTOURPOINTS_GLOBAL_H
