#ifndef TOOLGRAYMATCH_GLOBAL_H
#define TOOLGRAYMATCH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOOLGRAYMATCH_LIBRARY)
#  define TOOLGRAYMATCHSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TOOLGRAYMATCHSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TOOLGRAYMATCH_GLOBAL_H
