#ifndef FRMINPUTKEYBOARD_GLOBAL_H
#define FRMINPUTKEYBOARD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FRMINPUTKEYBOARD_LIBRARY)
#  define FRMINPUTKEYBOARDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FRMINPUTKEYBOARDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FRMINPUTKEYBOARD_GLOBAL_H
