#ifndef TOOLCOLORAREA_GLOBAL_H
#define TOOLCOLORAREA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOOLCOLORAREA_LIBRARY)
#  define TOOLCOLORAREASHARED_EXPORT Q_DECL_EXPORT
#else
#  define TOOLCOLORAREASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TOOLCOLORAREA_GLOBAL_H
