#ifndef TOOLMATCHCIRCLE_GLOBAL_H
#define TOOLMATCHCIRCLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOOLMATCHCIRCLE_LIBRARY)
#  define TOOLMATCHCIRCLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define TOOLMATCHCIRCLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TOOLMATCHCIRCLE_GLOBAL_H
