#ifndef LOGICCONDJUMP_GLOBAL_H
#define LOGICCONDJUMP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LOGICCONDJUMP_LIBRARY)
#  define LOGICCONDJUMPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LOGICCONDJUMPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LOGICCONDJUMP_GLOBAL_H
