#ifndef TOOLMATCHBLOB_GLOBAL_H
#define TOOLMATCHBLOB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOOLMATCHBLOB_LIBRARY)
#  define TOOLMATCHBLOBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TOOLMATCHBLOBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TOOLMATCHBLOB_GLOBAL_H
