#ifndef P2PCENTERPOINT_GLOBAL_H
#define P2PCENTERPOINT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(P2PCENTERPOINT_LIBRARY)
#  define P2PCENTERPOINTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define P2PCENTERPOINTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // P2PCENTERPOINT_GLOBAL_H
